apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: demo
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"
        keyvaultname: KEYVAULT_NAME
        keyvaultobjectname: SECRET_NAME
        keyvaultobjecttype: secret # OPTIONS: secret, key, cert
        keyvaultobjectversion: SECRET_VERSION
        resourcegroup: RESOURCE_GROUP
        subscriptionid: SUB_ID
        tenantid: TENANT_ID
